dmlblog/urls.py
from django.conf.urls import url
from . import views


app_name = "blog"
urlpatterns = [
    url(r"^$", views.post_list, name="post_list"),
    url(r"^drafts/$", views.post_draft_list, name="post_draft_list"),
    url(r"^post/(?P<pk>\d+)/$", views.post_detail, name="post_detail"),
    url(r"^post/new/$", views.post_new, name="post_new"),
    url(r"^post/(?P<pk>\d+)/edit/$", views.post_edit, name="post_edit"),
    url(r"^post/(?P<pk>\d+)/publish/$", views.post_publish, name="post_publish"),
    url(r"^post/(?P<pk>\d+)/unpublish/$", views.post_unpublish, name="post_unpublish"),
    url(r"^post/(?P<pk>\d+)/dremove/$", views.draft_remove, name="draft_remove"),
    url(r"^post/(?P<pk>\d+)/tag/$", views.tag_post, name="tag_post"),
    url(
        r"^post/(?P<pk>\d+)/comment/$",
        views.add_comment_to_post,
        name="add_comment_to_post",
    ),
    url(
        r"^comment/(?P<pk>\d+)/approve/$", views.comment_approve, name="comment_approve"
    ),
    url(r"^comment/(?P<pk>\d+)/remove/$", views.comment_remove, name="comment_remove"),
    url(r"^test/$", views.post_test, name="post_test"),
]

dmlgeo/urls.py
from django.conf.urls import url
from . import views

app_name = "dmlgeo"

urlpatterns = [
    # url(r'^$', views.chat_main, name='chat'),
    # url(r'^test/$', views.chat_test, name='test'),
]

dmlpolls/urls.py
from django.conf.urls import url
from . import views

app_name = 'dmlpolls'
urlpatterns = [
    # url(r'^index$', views.PollIndexView.as_view(), name='poll_index'),
    # url(r'^(?P<pk>[0-9]+)/$', views.PollDetailView.as_view(), name='poll_detail'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.PollResultsView.as_view(), name='poll_results'),


    url(r'^$', views.poll_list, name='poll_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.poll_detail, name='poll_detail'),
    url(r'^question/add/$', views.addpoll, name='add_poll'),
    url(r'^(?P<question_id>[0-9]+)/add_choice/$', views.add_choice, name='add_choice'),
    url(r'^(?P<pk>[0-9]+)/vote/$', views.vote, name='poll_vote'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.results, name='poll_results'),

    # url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    # url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

dmlsite/urls.py
from django_jinja import views as dj_jn_views
from django.conf.urls import url, include
from django.urls import re_path, path
# import django.contrib.auth.views    # The login views redirect to admin here, or to previous page in dmlmain
from django.contrib import admin
# from django.contrib.staticfiles.storage import staticfiles_storage
# from django.views.generic.base import RedirectView
from controlcenter.views import controlcenter
from django.conf.urls.static import static
from django.conf import settings

from typing import cast

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    path('admin/dashboard/', controlcenter.urls),
    # url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    # url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('dmlmain.urls')),
    url(r'^blog/', include('dmlblog.urls', namespace='blog')),
    re_path(r'^polls/', include('dmlpolls.urls', namespace='polls')),
    url(r'^comments/', include('dmlcomments.urls', namespace='comments')),
    url(r'^research/', include('dmlresearch.urls', namespace='research')),
    url(r'^chat/', include('dmlchat.urls', namespace='chat')),
]


# handler400 = dj_jn_views.BadRequest.as_view()
# handler403 = dj_jn_views.PermissionDenied.as_view()
handler404 = dj_jn_views.PageNotFound.as_view()
# handler500 = dj_jn_views.ServerError.as_view()

if settings.DEBUG: 
    urlpatterns += static(cast(str, settings.STATIC_URL), document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dmlpolls/models.py
from __future__ import annotations
from django.db import models
import datetime
from django.utils import timezone
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse
from dmlcomments.models import Comment

# for typing
from django.db.models import QuerySet
import typing as tp
from typing import Optional, Union, TypeVar, Any, Generic

if tp.TYPE_CHECKING:
    from django.db.models.expressions import Combinable
    from django.contrib.auth.models import User


_Q = TypeVar('_Q', bound='Question')


class QuestionQuerySet(QuerySet, Generic[_Q]):
    Model: _Q

    def _filter(self, *args: Any, **kwargs: Any) -> QuestionQuerySet[Question]:
        return self.filter(args, kwargs)


class Question(models.Model):
    id: models.AutoField[Union[Combinable, str, int], int]
    id = models.AutoField(primary_key=True)

    author: models.ForeignKey[Union[User, Combinable, None], Optional[User]]
    author = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.CASCADE)

    question_text: models.CharField[Union[str, int, Combinable], str]
    question_text = models.CharField(max_length=200)

    pub_date = models.DateTimeField('date published', auto_now_add=True)
    end_date = models.DateTimeField(blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    poll_comments = GenericRelation(Comment, related_query_name='poll_comments')
    choice_set = GenericRelation('Choice', related_query_name='choice_set')

    myobjects: models.Manager[Question] = models.Manager.from_queryset(QuestionQuerySet)

    def __str__(self) -> str:
        return self.question_text

    def was_published_recently(self) -> Optional[bool]:
        """True is recent, false if not, None is error"""
        now = timezone.now()
        if self.pub_date is not None:
            return now - datetime.timedelta(days=7) <= self.pub_date <= now
        else:
            return None
        # raise AttributeError("Pub_date attribute missing for this question")

        # was_published_recently.admin_order_field = 'pub_date'
        # was_published_recently.boolean = True
        # was_published_recently.short_description = 'Published recently?'
        # poll_author.admin_order_field = 'author'

    def get_absolute_url(self) -> str:
        return reverse('dmlpolls:poll_detail', kwargs={"pk": self.pk})

    @property
    def comments(self) -> QuerySet[Comment]:
        instance = self
        qs: QuerySet[Comment] = Comment.myobjects.filter_by_instance(instance=instance)  # type: ignore
        return qs

    @property
    def get_content_type(self) -> ContentType:
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.choice_text


class Opinion(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_vote = models.ForeignKey(Choice, on_delete=models.CASCADE)

dmlpolls/forms.py
from django import forms
from .models import Question, Choice  # , Votes
from pagedown.widgets import PagedownWidget


class AddPollForm(forms.ModelForm):

    # object_id = forms.IntegerField(widget=forms.HiddenInput)
    question_text = forms.CharField(label="Question", widget=PagedownWidget())
    pub_date = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Question
        fields = ['question_text', ]  # "tags""image" add comment form

    def clean_question_text(self) -> str:
        question_text: str = self.cleaned_data.get('question_text')
        return question_text


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['choice_text', ]

dmlpolls/views.py
from django.shortcuts import get_object_or_404, render  # , redirect
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
# from django.contrib.auth.decorators import login_required
from .forms import AddPollForm, ChoiceForm
from .models import Choice, Question  # , Opinion
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from dmlcomments.models import Comment
from dmlcomments.forms import CommentForm
from django.db.models import QuerySet
from django.core.handlers.wsgi import WSGIRequest
from typing import Optional, cast


def poll_list(request: HttpRequest) -> HttpResponse:
    questions = Question.myobjects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
    # queryset_list = Question.objects.all()
    c_type = ContentType.objects.get_for_model(Question)
    # post_id = posts.values_list('id')
    poll_comments = Comment.myobjects.filter(content_type=c_type)
    counts = 1
    for question in questions:
        for comment in poll_comments:
            if comment.content_object and comment.content_object.id == question.id:
                counts += 1
                question.poll_comments.count = counts
    query = request.GET.get("q")
    if query:
        questions = questions.filter(Q(question_text__icontains=query) |
                                     Q(author__username__icontains=query) |
                                     Q(author__first_name__icontains=query) |
                                     Q(author__last_name__icontains=query)).distinct()
    paginator = Paginator(questions, 5)
    page_request_var = "polls_page"
    page = request.GET.get(page_request_var)
    try:
        if isinstance(page, (str, int)):
            page_set = paginator.page(page)
        else:
            raise TypeError
    except (PageNotAnInteger, TypeError):  # if not enough, give first page
        page_set = paginator.page(1)
    except EmptyPage:  # if too many, give last page
        page_int = paginator.num_pages
        page_set = paginator.page(page_int)
    context = {'questions': questions, 'page_request_var': page_request_var, 'obj_list': page_set}
    return render(request, 'dmlpolls/poll_list.html', context)


def poll_detail(request: WSGIRequest, pk: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=pk)
    comments = question.comments
    counts = 1
    for comment in comments:
        if comment.content_object and comment.content_object.id == question.id:
            counts += 1
            question.poll_comments.count = counts
    initial_data = {"content_type": question.get_content_type,
                    "object_id": question.id,
                    "author_id": request.user}

    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid():
        content_type_str: str = form.cleaned_data.get("content_type")
        content_type_model = content_type_str.split()[-1]
        content_type = ContentType.objects.get(model=content_type_model)
        obj_id = form.cleaned_data.get('object_id')
        content_data = form.cleaned_data.get("text")
        parent_obj = None
        try:
            parent_id: Optional[int] = int(cast(str, request.POST.get("parent_id")))
        except Exception:
            parent_id = None

        if parent_id is not None:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()
        new_comment, created = Comment.objects.get_or_create(
            author=request.user,
            content_type=content_type,
            object_id=obj_id,
            text=content_data,
            parent=parent_obj,			)
        if new_comment.content_object:
            return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    context = {"form": form, 'question': question, "comments": comments, }
    return render(request, 'dmlpolls/poll_detail.html', context)


class PollIndexView(ListView):
    template_name = 'dmlpolls/poll_index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self) -> QuerySet:
        """    Return the last five published questions (not including those set to be
        published in the future).    """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class PollDetailView(DetailView):
    model = Question
    template_name = 'dmlpolls/poll_detail.html'

    def get_queryset(self) -> 'QuerySet[Question]':
        """Excludes any questions that aren't published yet."""
        return Question.objects.filter(pub_date__lte=timezone.now())


class PollResultsView(DetailView):
    model = Question
    template_name = 'dmlpolls/poll_results.html'

    def get_queryset(self) -> 'QuerySet[Question]':
        """Excludes any questions that aren't published yet."""
        return Question.objects.filter(pub_date__lte=timezone.now())


def addpoll(request: HttpRequest) -> HttpResponse:
    form = AddPollForm(request.POST or None)
    if form.is_valid():  # on submit
        poll = form.save(commit=False)
        poll.author = request.user
        poll.save()
        # question_text = form.cleaned_data.get('question_text')
        # questions = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')

        # return render(request, 'dmlpolls/poll_list.html', {'questions': questions})
        return poll_list(request)
        # context ={'form':form}
        # return render(request, 'dmlpolls/add_choice.html', context)
    else:  # on first load
        form = AddPollForm()
        context = {'form': form}
        return render(request, 'dmlpolls/add_poll.html', context)


def add_choice(request: HttpRequest, question_id: int) -> HttpResponse:
    question = Question.objects.get(pk=question_id)
    form = ChoiceForm(request.POST)
    if form.is_valid():
        form.save(commit=False)
        # addpoll.question = question
        # addpoll.vote = 0
        # addpoll.question.save()
        return render(request, 'dmlpolls/poll_detail.html', {'question': question})
        # return HttpResponse('gbhbetg')
    else:
        form = ChoiceForm()
        return render(request, 'dmlpolls/add_choice.html', {'form': form, 'question_id': question_id, })


def vote(request: HttpRequest, pk: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=pk)
    try:
        selected_choice: Choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'dmlpolls/poll_detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a user hits the Back button.
        return HttpResponseRedirect(reverse('dmlpolls:poll_results', args=[question.id]))
        # return HttpResponse("placeholder for votes number %s." % question_id)


def results(request: HttpRequest, pk: int) -> HttpResponse:
    question = get_object_or_404(Question, pk=pk)
    return render(request, 'dmlpolls/poll_results.html', {'question': question})

dmlpolls/templates/dmlpolls/add_choice.html
{% extends 'dmlmain/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<p>Add Choices</p>
    <form id="choice" name="" action="" method="post"> {% csrf_token %}
    {{form|crispy}}
	    <fieldset>
            <label for="id_choice">Choice: </label>{{form.choice}}

            <input type="submit" value="Submit" />
        </fieldset>
    </form>


{% endblock %}

dmlpolls/templates/dmlpolls/add_poll.html
{% extends 'dmlmain/base.html' %}
{% load crispy_forms_tags %}
{% block head_extra %} {{ form.media }} {% endblock head_extra%}

{% block content %}

<form method='POST' action=''>{%csrf_token %}
{{form|crispy}}
	<input type='submit', value='Submit'/>
</form>

{% endblock %}

dmlpolls/templates/dmlpolls/detail.html
{% extends 'dmlmain/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load markdown_deux_tags %}
{% load humanize %}
{% block head_title %}{{ question.title }} | {{ block.super }}{% endblock head_title %}
{% block head_extra %} {{ form.media }}
<link rel="stylesheet" href="{% static 'css/polls.css' %}"/>
<link rel="stylesheet" href="{% static 'dmlcomments/dmlcomments.css' %}"/>
<script type="text/javascript" src="{% static 'dmlcomments/dmlcomments.js' %}" defer></script>
{% endblock head_extra%}


{% block content %}

<h1>{{ question.question_text }}</h1>
<h2><small>{{question.author}} - {{question.pub_date|naturaltime}}</small></h2>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'dmlpolls:poll_vote' question.id %}" method="post">{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="vote" class="btn btn-default" />
</form>

<br>
<hr>
<br>

{% if comments.count > 0 %}  {{comments.count}} comment{% if comments.count > 1 %}s {% endif %}{% endif %}
<div class="btn btn-default" id="commentShowButton">Add comment</div>
<div id="commentShow">
	<h3>Add comment:</h3>
		<form action="." method="POST" class="post-form"> {% csrf_token %}
			{{form|crispy}}
			<button type="submit" class="save btn btn-default">Submit</button>
		</form>
</div>

{% for comment in comments %}
<blockquote class="comment">


	{{ comment.text|markdown }}
	<span class='date'>{{ comment.author }} - {{ comment.created_date|naturaltime}}
		 {% if comment.children.count > 0 %} | {{ comment.children.count }} repl{% if comment.children.count > 1 %}ies {% elif comment.children.count == 1 %}y
		 {% endif %} |<a class="replyShowButton" href="#">Show Thread</a><a class="" href="{{ comment.get_absolute_url }}">(Link)</a>{% endif %}{% if request.user == comment.author %}<a class="" href="{{ comment.get_delete_url }}">Delete</a>{% endif %}</span>


	<div class='replyShow'>
	{% for child_comment in comment.children %}
	<blockquote class="reply">
		{{ child_comment.text|markdown }}
		<span><p> by {{ child_comment.author }} - {{ child_comment.created_date|naturaltime}}<p>
		{% if request.user == child_comment.author %}<a class="" href="{{ child_comment.get_delete_url }}">Delete</a>{% endif %}</span>
	</blockquote>
	{% endfor %}
</div>

	<span><a class="addReplyShowButton">| Reply</a></span>
	<div class='addReplyShow'>
		<form action="." method="POST"> {% csrf_token %}
			{{form|crispy}}
			<input type='hidden' name='parent_id' value="{{ comment.id }}"/>
			<button type="submit" class="save btn btn-default">Submit</button>
		</form>
	</div>

{% if user.is_authenticated or comment.approved_comment %}
{% elif not comment.approved_comment and user.is_staff %}
<a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
<a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>

{% endif %}
</blockquote>
{% empty %}
 	<p>No comments here yet :(  Login to comment</p>
{% endfor %}

{% endblock %}

dmlpolls/templates/dmlpolls/index.html
{% extends 'dmlmain/base.html' %}

{% block content %}

	<h1>Recent Polls</h1>
		{% if latest_question_list %}
		<ul>
		{% for question in latest_question_list %}
        <li><a href="{% url 'polls:poll_detail' question.id %}">{{ question.question_text }}</a>{{question.author}}{{question.pub_date}}</li>
		{% endfor %}
		</ul>
		{% else %}
		<p>No recent polls are available.</p>
		{% endif %}
		<p>See all <a href="{% url 'polls:poll_list' %}">previous polls here</a></p>


{% endblock %}

dmlpolls/templates/dmlpolls/poll_detail.html
{% extends 'dmlmain/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load markdown_deux_tags %}
{% load humanize %}
{% block head_title %}{{ question.title }} | {{ block.super }}{% endblock head_title %}
{% block head_extra %} {{ form.media }}
<link rel="stylesheet" href="{% static 'css/polls.css' %}"/>
<link rel="stylesheet" href="{% static 'dmlcomments/dmlcomments.css' %}"/>
<script type="text/javascript" src="{% static 'dmlcomments/dmlcomments.js' %}" defer></script>
{% endblock head_extra%}


{% block content %}

<h1>{{ question.question_text }}</h1>
<h2><small>{{question.author}} - {{question.pub_date|naturaltime}}</small></h2>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'dmlpolls:poll_vote' question.id %}" method="post">{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="vote" class="btn btn-default" />
</form>

<br>
<hr>
<br>

<span>{% if comments.count > 0 %}  {{ question.poll_comments.count }} comments in {{comments.count}} thread{% if comments.count > 1 %}s {% endif %}{% endif %}
<div class="btn btn-default" id="commentShowButton">Add comment</div></span>
<div id="commentShow">
	<h3>Add comment:</h3>
		<form action="." method="POST" class="post-form"> {% csrf_token %}
			{{form|crispy}}
			<button type="submit" class="save btn btn-default">Submit</button>
		</form>
</div>

{% for comment in comments %}
<blockquote class="comment">
	{{ comment.text|markdown }}

	<span class='date'>{{ comment.author }} - {{ comment.created_date|naturaltime}}
		 {% if comment.children.count > 0 %} | {{ comment.children.count }} repl{% if comment.children.count > 1 %}ies {% elif comment.children.count == 1 %}y
		 {% endif %} |<a class="replyShowButton" href="#">Show Thread</a><a class="" href="{{ comment.get_absolute_url }}">(Link)</a>{% endif %}{% if request.user == comment.author %}<a class="" href="{{ comment.get_delete_url }}">Delete</a>{% endif %}</span>


	<div class='replyShow'>
	{% for child_comment in comment.children %}
	<blockquote class="reply">
		{{ child_comment.text|markdown }}
		<span><p> by {{ child_comment.author }} - {{ child_comment.created_date|naturaltime}}<p>
		{% if request.user == child_comment.author %}<a class="" href="{{ child_comment.get_delete_url }}">Delete</a>{% endif %}</span>

	</blockquote>
	{% endfor %}
	</div>

	<span><a class="addReplyShowButton">| Reply</a></span>
	<div class='addReplyShow'>
		<form action="." method="POST"> {% csrf_token %}
			{{form|crispy}}
			<input type='hidden' name='parent_id' value="{{ comment.id }}"/>
			<button type="submit" class="save btn btn-default">Submit</button>
		</form>
	</div>

{% if user.is_authenticated or comment.approved_comment %}
{% elif not comment.approved_comment and user.is_staff %}
<a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
<a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>

{% endif %}
</blockquote>
{% empty %}
 	<p>No comments here yet :(  Login to comment</p>
{% endfor %}

{% endblock %}

dmlpolls/templates/dmlpolls/poll_index.html
{% extends 'dmlmain/base.html' %}

{% block content %}

	<h1>Recent Polls</h1>
		{% if latest_question_list %}
		<ul>
		{% for question in latest_question_list %}
        <li><a href="{% url 'polls:poll_detail' question.id %}">{{ question.question_text }}</a>{{question.author}}{{question.pub_date}}</li>
		{% endfor %}
		</ul>
		{% else %}
		<p>No recent polls are available.</p>
		{% endif %}
		<p>See all <a href="{% url 'polls:poll_list' %}">previous polls here</a></p>


{% endblock %}

dmlpolls/templates/dmlpolls/poll_list.html
{% extends 'dmlmain/base.html' %}

{% block content %}

<div class = "list_search">
<form method='GET' action='' class="row">
		<div class="input-group col-sm-6 col-sm-offset-6">
			<input class="form-control" type='text' name='q' placeholder='Search Polls' value='{{request.GET.q}}'/>
		<span class="input-group-btn">
			<button class="btn btn-default" type='submit' value='Search'><i class="fa fa-search"></i>&nbsp;</button>
		</span>
	</div>
</form>
</div>


{% for question in obj_list%}
<div class="post">
    <h1><a href="{% url 'polls:poll_detail' question.id %}">{{ question.question_text }}</a></h1>
  	<div class="date">
	{{poll.author}} - {{poll.pub_date}}
	</div>
</div>


<div>
		<a href="{% url 'polls:poll_detail' question.id %}"> {{question.poll_comments.count}}
			comment{% if question.poll_comments.count > 1 or question.poll_comments.count == 0 %}s {% endif %}</a>

</div>
{% endfor %}


{% include "dmlmain/pagination.html" %}

{% endblock %}

dmlpolls/templates/dmlpolls/poll_results.html
{% extends 'dmlmain/base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:poll_detail' question.id %}">Vote again?</a>


{% endblock %}

dmlpolls/templates/dmlpolls/results.html
{% extends 'dmlmain/base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:poll_detail' question.id %}">Vote again?</a>


{% endblock %}

dmlpolls/templates/dmlpolls/votes.html
{% extends 'dmlmain/base.html' %}

{% block content %}

<h1>{{ question.question_text }}</h1>

{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:poll_vote' question.id %}" method="post">{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

{% endblock %}