dmlblog/urls.py
from django.conf.urls import url
from . import views


app_name = "blog"
urlpatterns = [
    url(r"^$", views.post_list, name="post_list"),
    url(r"^drafts/$", views.post_draft_list, name="post_draft_list"),
    url(r"^post/(?P<pk>\d+)/$", views.post_detail, name="post_detail"),
    url(r"^post/new/$", views.post_new, name="post_new"),
    url(r"^post/(?P<pk>\d+)/edit/$", views.post_edit, name="post_edit"),
    url(r"^post/(?P<pk>\d+)/publish/$", views.post_publish, name="post_publish"),
    url(r"^post/(?P<pk>\d+)/unpublish/$", views.post_unpublish, name="post_unpublish"),
    url(r"^post/(?P<pk>\d+)/dremove/$", views.draft_remove, name="draft_remove"),
    url(r"^post/(?P<pk>\d+)/tag/$", views.tag_post, name="tag_post"),
    url(
        r"^post/(?P<pk>\d+)/comment/$",
        views.add_comment_to_post,
        name="add_comment_to_post",
    ),
    url(
        r"^comment/(?P<pk>\d+)/approve/$", views.comment_approve, name="comment_approve"
    ),
    url(r"^comment/(?P<pk>\d+)/remove/$", views.comment_remove, name="comment_remove"),
    url(r"^test/$", views.post_test, name="post_test"),
]

dmlgeo/urls.py
from django.conf.urls import url
from . import views

app_name = "dmlgeo"

urlpatterns = [
    # url(r'^$', views.chat_main, name='chat'),
    # url(r'^test/$', views.chat_test, name='test'),
]

dmlsite/urls.py
from django_jinja import views as dj_jn_views
from django.conf.urls import url, include
from django.urls import re_path, path
# import django.contrib.auth.views    # The login views redirect to admin here, or to previous page in dmlmain
from django.contrib import admin
# from django.contrib.staticfiles.storage import staticfiles_storage
# from django.views.generic.base import RedirectView
from controlcenter.views import controlcenter
from django.conf.urls.static import static
from django.conf import settings

from typing import cast

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    path('admin/dashboard/', controlcenter.urls),
    # url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    # url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('dmlmain.urls')),
    url(r'^blog/', include('dmlblog.urls', namespace='blog')),
    re_path(r'^polls/', include('dmlpolls.urls', namespace='polls')),
    url(r'^comments/', include('dmlcomments.urls', namespace='comments')),
    url(r'^research/', include('dmlresearch.urls', namespace='research')),
    url(r'^chat/', include('dmlchat.urls', namespace='chat')),
]


# handler400 = dj_jn_views.BadRequest.as_view()
# handler403 = dj_jn_views.PermissionDenied.as_view()
handler404 = dj_jn_views.PageNotFound.as_view()
# handler500 = dj_jn_views.ServerError.as_view()

if settings.DEBUG: 
    urlpatterns += static(cast(str, settings.STATIC_URL), document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dmlblog/forms.py
from django import forms
# from django.views.generic import ListView  # , DetailView
from .models import Post  # , Comment
from pagedown.widgets import PagedownWidget

# from django.db.models.query import QuerySet


class PostForm(forms.ModelForm):
    # template="path/to/template.html", css=("custom/css1.css", "custom/css2.css"))
    text = forms.CharField(widget=PagedownWidget())
    published_date = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Post
        fields = (
            "title",
            "text",
            "tags",
            "video",
            "image",
            "image_width",
            "image_height",
            "draft",
            "published_date",
        )


"""
class TagMixin(object):
    def get_context_data(self, **kwargs):
        context = super(TagMixin, self).get_context_data(**kwargs)
        context["tags"] = Tag.objects.all()
        return context


class TagIndexView(TagMixin, ListView):
    paginate_by = 5  # "5"

    def get_queryset(self) -> "QuerySet[Post]":
        return Post.objects.filter(tags__slug=self.kwargs.get("pk"))
"""

dmlblog/views.py
from django.db.models.manager import Manager
from django.http.response import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, HttpResponse, HttpRequest
from django.core.handlers.wsgi import WSGIRequest
from django.utils import timezone
from django.contrib import messages

# from .utils import get_read_time
from .models import Post
from .forms import PostForm  # , TagIndexView, TagMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger, InvalidPage
from django.contrib.auth.decorators import login_required
from django.db.models import Q  # , Prefetch
from django.contrib.contenttypes.models import ContentType
from dmlcomments.models import Comment
from dmlcomments.forms import CommentForm

try:
    from urllib.parse import quote_plus
except ImportError:
    pass

from typing import cast, Union


def post_test(request: HttpRequest) -> HttpResponse:
    posts = Post.objects.all()
    c_type = ContentType.objects.get_for_model(Post)
    post_id = posts.values_list("id")
    post_comments = Comment.objects.filter(content_type=c_type)
    # content_object = post_comment.content_object #gets poll/post the comment is from
    # content_id = comment.content_object.id
    # p_c_id = post_comment.content_object.id
    # post_comments = Post.objects.prefetch_related('post_comments').filter(content_type=c_type, object_id__in=post_id)
    # post_comments = Comment.objects.filter(content_type__pk=c_type.id, object_id=post_id)
    context = {"posts": posts, "post_comments": post_comments, "post_id": post_id}
    return render(request, "dmlblog/post_test.html", context)


def post_list(request: HttpRequest) -> HttpResponse:
    posts: Manager[Post] = (
        Post.objects.filter(draft=False)
        .filter(published_date__lte=timezone.now())
        .order_by("published_date")
        .reverse()
    )
    c_type = ContentType.objects.get_for_model(Post)
    # post_id = posts.values_list('id')
    post_comments: Manager[Comment] = Comment.objects.filter(content_type=c_type)
    counts = 1
    for post in posts:
        for comment in post_comments:
            if comment.content_object is not None and comment.content_object.id == post.id:
                counts += 1
                post.post_comments.count = counts

    query = request.GET.get("q")
    if query:
        posts = posts.filter(
            Q(title__icontains=query)
            | Q(author__username__icontains=query)
            | Q(author__first_name__icontains=query)
            | Q(author__last_name__icontains=query)
            | Q(text__icontains=query)
        ).distinct()
    paginator = Paginator(posts, 5)
    page_request_var = "post_page"
    page: Union[int, str, None] = request.GET.get(page_request_var)
    # print(paginator.count)
    # print(paginator.num_pages)
    try:
        if page is None:
            page = 1
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)  # if not enough, give first page
    except (EmptyPage or InvalidPage):
        # if too many, give last page
        number_pages = paginator.num_pages
        queryset = paginator.page(number_pages)
    context = {
        "posts": posts,
        "post_comments": post_comments,
        "counts": counts,
        "page_request_var": page_request_var,
        "obj_list": queryset,
    }
    return render(request, "dmlblog/post_list.html", context)


def post_detail(request: WSGIRequest, pk: str) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    share_string = quote_plus(post.text)
    # comments = post.comments #FK changed to GFK
    # form = CommentForm()
    comments = Comment.objects.filter_by_instance(post)  # aka = post.comments
    counts = 1
    for comment in comments:
        if (
            isinstance(comment.content_object, Post)
            and comment.content_object.id == post.id
        ):
            counts += 1
            post.post_comments.count = counts
    initial_data = {
        "content_type": post.get_content_type,
        "object_id": post.id,
        "author_id": request.user,
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid():
        c_data = form.cleaned_data.get("content_type")  # "blog | post"
        app_label = c_data.split()[0]
        model = c_data.split()[-1]
        content_type = ContentType.objects.get_by_natural_key(app_label=app_label, model=model)

        # pid = int(form.cleaned_data.get("parent_id"))
        # content_type = ContentType.objects.get_for_id(pid)

        obj_id = form.cleaned_data.get("object_id")
        content_text = form.cleaned_data.get("text")
        parent_obj = None
        try:
            parent_id_str = request.POST.get("parent_id")
            if parent_id_str is not None:
                parent_id = int(parent_id_str)
            else:
                parent_id = 0
        except Exception:
            parent_id = 0

        if parent_id is True:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()
        new_comment: Comment
        new_comment, created = Comment.objects.get_or_create(
            author=request.user,
            content_type=content_type,
            object_id=obj_id,
            text=content_text,
            parent=parent_obj,
        )
        if new_comment.content_object is not None:
            return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    context = {
        "post": post,
        "share_string": share_string,
        "comments": comments,
        "form": form,
    }
    return render(request, "dmlblog/post_detail.html", context)


@login_required
def post_new(request: WSGIRequest) -> HttpResponse:
    if request.method == "POST":
        form = PostForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            if post.draft:
                messages.success(request, "New draft created!")
            else:
                messages.success(request, "New post created!")
                return redirect("blog:post_detail", pk=post.pk)
        else:
            messages.error(request, "New post failed!")
    else:
        form = PostForm()
    context = {"form": form}
    return render(request, "dmlblog/post_edit.html", context)


@login_required
def post_edit(request: WSGIRequest, pk: str) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST or None, request.FILES or None, instance=post)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            form.save_m2m()
            messages.success(cast(WSGIRequest, request), "Post updated")
            return redirect("blog:post_detail", pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, "dmlblog/post_edit.html", {"form": form})


@login_required
def post_unpublish(request: WSGIRequest, pk: str) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    post.unpublish()
    messages.success(request, "Post unpublished to drafts")
    return redirect("blog:post_list")


@login_required
def post_draft_list(request: HttpRequest) -> HttpResponse:
    drafts = Post.objects.filter(draft=True).order_by("created_date")
    return render(request, "dmlblog/post_draft_list.html", {"drafts": drafts})


@login_required
def post_publish(request: WSGIRequest, pk: str) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect("blog:post_detail", pk=post.pk)


@login_required
def draft_remove(request: WSGIRequest, pk: str) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    messages.success(request, "Draft deleted")
    return redirect("blog:post_draft_list")


def add_comment_to_post(request: WSGIRequest, pk: str) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect("blog:post_detail", pk=post.pk)
    else:
        form = CommentForm()
    return render(request, "dmlblog/add_comment_to_post.html", {"form": form})


@login_required
def comment_approve(request: HttpRequest, pk: str) -> HttpResponse:
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    if isinstance(comment.content_object, Post):
        post_pk = comment.content_object.pk
        return redirect("dmlblog.views.post_detail", pk=post_pk)
    else:
        raise(TypeError)


@login_required
def comment_remove(request: WSGIRequest, pk: str) -> HttpResponse:
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    if isinstance(comment.content_object, Post):
        post_pk = comment.content_object.pk
        return redirect("dmlblog.views.post_detail", pk=post_pk)
    else:
        raise Http404("Comments can only be removed from Post at this time")


def tag_post(request: HttpRequest, pk: str) -> HttpResponse:
    post = get_object_or_404(Post, pk=pk)
    return redirect("dmlblog.views.post_detail", pk=post.pk)

dmlblog/templates/dmlblog/add_comment_to_post.html
{% extends 'dmlmain/base.html' %}
{% load crispy_forms_tags %}
{% block head_extra %} {{ form.media }} {% endblock head_extra%}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

dmlblog/templates/dmlblog/post_detail.html
{% extends 'dmlmain/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load embed_video_tags %}
{% load markdown_deux_tags %}
{% load humanize %}
{% block head_title %}{{ post.title }} | {{ block.super }}{% endblock head_title %}
{% block head_extra %} {{ form.media }}
<link rel="stylesheet" href="{% static 'css/blog.css' %}"/>
<link rel="stylesheet" href="{% static 'dmlcomments/dmlcomments.css' %}"/>
<script type="text/javascript" src="{% static 'dmlcomments/dmlcomments.js' %}" defer></script>
{% endblock head_extra %}

{% block content %}


    <div class="post">
        {% if post.published_date %}
            <div class="date">
                <span class="glyphicon glyphicon-saved"></span> {{ post.published_date }}

            </div>
        {% else %}
			{% if user.is_authenticated and post.draft %}
				<p><span style="color:red;">Draft</span> created: {{ post.created_date }}</p>
				<a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}"><span class="glyphicon glyphicon-save"></span></a>
        	{% endif %}
		{% endif %}

        {% if user.is_authenticated %}
        	<a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
			<a class="btn btn-default" href="{% url 'blog:post_unpublish' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
		{% endif %}
			<a class="btn btn-default" href="/blog/drafts/"><span class="glyphicon glyphicon-plus"></span></a>

			<h1>{{ post.title }}</h1>
			 {{ post.text|markdown }}

			 <p>Read time: 	{% if post.read_time < 1 %} < 1 minute
				 			{% else %}{{ post.read_time }} minutes
							{% endif %}</p>
			<p>Author: {{ post.author }}</p>


<p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>
<hr/>
</p>
		{% if post.video %}
		{% video post.video %}
			{% video post.video as my_video %}
		{% endvideo %}
		{% endif %}


		{% if post.image %}
			 <img src="{{ post.image.url }}" class ='img-responsive'/>
		{% endif %}


		<span class="tags">
		{% for tag in post.tags.all %}
			<p># {{ tag }}</p>
		{% endfor %}
		</span>


    </div>

	<script>
		$(document).ready(function(){
			$(".post img").addClass("img-responsive")
		})

		</script>

       <!--	<a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>
	{% for comment in post.comments.all %}
		{% if user.is_authenticated or comment.approved_comment %}
    		<div class="comment">
				{{ comment.author }}
					<div class="date">
            	{{ comment.created_date }}
		{% elif not comment.approved_comment %}
        	 	<a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                	<a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
		{% endif %}
					</div>
        		<p>{{ comment.text|linebreaks }}</p>
    		</div>
	{% empty %}
    		<p>No comments here yet :(
    		   Login to comment</p>
	{% endfor %} -->

<span>{% if comments.count > 0 %}  
{{post.post_comments.count}} comments in {{comments.count}} thread
{% if comments.count > 1 %}s {% endif %}
{% endif %}

<div class="btn btn-default" id="commentShowButton">Add comment</div></span>
<div id="commentShow">
	<h3>Add comment:</h3>
		<form action="." method="POST" class="post-form"> {% csrf_token %}
			{{form|crispy}}
			<button type="submit" class="save btn btn-default">Submit</button>
		</form>
</div>

{% for comment in comments %}
<blockquote class="comment">

	{{ comment.text|markdown }}
	<span class='date'>{{ comment.author }} - {{ comment.created_date|naturaltime}}
		 {% if comment.children.count > 0 %} | {{ comment.children.count }} repl{% if comment.children.count > 1 %}ies {% elif comment.children.count == 1 %}y
		 {% endif %} |<a class="replyShowButton" href="#">Show Thread</a><a class="" href="{{ comment.get_absolute_url }}">(Link)</a>{% endif %}{% if request.user == comment.author %}<a class="" href="{{ comment.get_delete_url }}">Delete</a>{% endif %}</span>

		 <span class='date'>{{ comment.author }} - {{ comment.created_date|naturaltime}}
 			 {% if comment.children.count > 0 %} | {{ comment.children.count }} repl{% if comment.children.count > 1 %}ies {% elif comment.children.count == 1 %}y
 			 {% endif %} |<a class="replyShowButton" href="#">Show Thread</a><a class="" href="{{ comment.get_absolute_url }}">(Link)</a>{% endif %}{% if request.user == comment.author %}<a class="" href="{{ comment.get_delete_url }}">Delete</a>{% endif %}</span>


 		<div class='replyShow'>
 		{% for child_comment in comment.children %}
 		<blockquote class="reply">
 			{{ child_comment.text|markdown }}
 			<span><p> by {{ child_comment.author }} - {{ child_comment.created_date|naturaltime}}<p>
 			{% if request.user == child_comment.author %}<a class="" href="{{ child_comment.get_delete_url }}">Delete</a>{% endif %}</span>

 		</blockquote>
 		{% endfor %}
 		</div>

 		<span><a class="addReplyShowButton">| Reply</a></span>
 		<div class='addReplyShow'>
 			<form action="." method="POST"> {% csrf_token %}
 				{{form|crispy}}
 				<input type='hidden' name='parent_id' value="{{ comment.id }}"/>
 				<button type="submit" class="save btn btn-default">Submit</button>
 			</form>
 		</div>

 	{% if user.is_authenticated or comment.approved_comment %}

 	{% elif not comment.approved_comment and user.is_staff %}
 	<a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
 	<a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>

 	{% endif %}
</blockquote>
{% empty %}
	<p>No comments here yet :(  Login to comment</p>
{% endfor %}



{% endblock %}

dmlblog/templates/dmlblog/post_draft_list.html
{% extends 'dmlmain/base.html' %}
{% load markdown_deux_tags %}

{% block content %}

<div class = "list_search">
<form method='GET' action='' class="row">
		<div class="input-group col-sm-6 col-sm-offset-6">
			<input class="form-control" type='text' name='q' placeholder='Search Drafts' value='{{request.GET.q}}'/>
		<span class="input-group-btn">
			<button class="btn btn-default" type='submit' value='Search'><i class="fa fa-search"></i>&nbsp;</button>
		</span>
	</div>
</form>
</div>

{% if user.is_authenticated %}
			{% for post in drafts %}

				<div class="post">
				<p class="date"><span style="color:red;">Draft</span> created: {{ post.created_date|date:'d-m-Y' }}</p>
				<h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
				<a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}"><span class="glyphicon glyphicon-save"></span></a>

				<a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
				<a class="btn btn-default" href="{% url 'blog:draft_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>

			</p>	{{ post.text|markdown|truncatewords:50 }}
				</div>
			{% empty %}
					<h1>No drafts awaiting publication</h1>
					<h1>Click here to author a new post:&nbsp;&nbsp;<a href="{% url 'blog:post_new' %}"><span class="glyphicon glyphicon-edit"></span></a></h1>
			{% endfor %}
{% endif %}

<script>
	$(document).ready(function(){
		$(".post img").addClass("img-responsive")
	})

	</script>

{% endblock %}

dmlblog/templates/dmlblog/post_edit.html
{% extends 'dmlmain/base.html' %}
{% load crispy_forms_tags %}
{% load markdown_deux_tags %}
{% block head_extra %} {{ form.media }} {% endblock head_extra%}

{% block content %}
    <h1>New post</h1>
    <form method="POST" enctype='multipart/form-data' class="post-form">{% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="save btn btn-default">Save</button>

    </form>
{% endblock %}

dmlblog/templates/dmlblog/post_list.html
{% extends 'dmlmain/base.html' %}
{% load markdown_deux_tags %}
{% load humanize %}
{% block content %}

<div class = "list_search">
<form method='GET' action='' class="row">
		<div class="input-group col-sm-6 col-sm-offset-6">
			<input class="form-control" type='text' name='q' placeholder='Search Posts' value='{{request.GET.q}}'/>
		<span class="input-group-btn">
			<button class="btn btn-default" type='submit' value='Search'><i class="fa fa-search"></i>&nbsp;</button>
		</span>
	</div>
</form>
</div>

{% for post in obj_list %}
{% if post.draft is False and post.published_date %}
	<div class="post">
			<h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>

			<div class="date">
            		<span>{{ post.author }} - {{ post.published_date|naturaltime }}</span>
			</div>

					{{ post.text|markdown|truncatewords:50 }}

				{% if post.image %}
						<div class = "thumbdiv">
						<a href="{% url 'blog:post_detail' pk=post.pk %}"><img src="{{ post.image.url }}" class ='img-responsive thumb' /></a>
						</div>
				{% endif %}

					<span class="tags"><p># {% for tag in post.tags.all %}{{ tag }}</p>{% endfor %}</span>



				<div>
						<a href="{% url 'blog:post_detail' pk=post.pk %}"> {{post.post_comments.count}}
							comment{% if post_comments.count > 1 or post_comments.count == 0 %}s {% endif %}</a>

				</div>





				</div>
	{% endif %}
{% endfor %}

<script>
	$(document).ready(function(){
		$(".post img").addClass("img-responsive")
	})
</script>

{% include "dmlmain/pagination.html" %}

{% endblock %}

dmlblog/templates/dmlblog/post_test.html
{% extends 'dmlmain/base.html' %}
{% block content %}



{% for post in posts %}

		<div class="post">
			<div>{{ post.title }}</div>
			<div>{{ post.author }}</div>
			<div>{{ post.text }}</div>
			<div>{{ post_comments.count }}</div>
			<div>{% for post_comment in post_comments %}
						{% if post_comment.content_object.id == post.id %}
							{{ post_comment }}
						{% endif %}
				{% endfor %}</div>



		</div>
{% endfor %}



{% endblock %}