dmlblog/urls.py
from django.conf.urls import url
from . import views


app_name = "blog"
urlpatterns = [
    url(r"^$", views.post_list, name="post_list"),
    url(r"^drafts/$", views.post_draft_list, name="post_draft_list"),
    url(r"^post/(?P<pk>\d+)/$", views.post_detail, name="post_detail"),
    url(r"^post/new/$", views.post_new, name="post_new"),
    url(r"^post/(?P<pk>\d+)/edit/$", views.post_edit, name="post_edit"),
    url(r"^post/(?P<pk>\d+)/publish/$", views.post_publish, name="post_publish"),
    url(r"^post/(?P<pk>\d+)/unpublish/$", views.post_unpublish, name="post_unpublish"),
    url(r"^post/(?P<pk>\d+)/dremove/$", views.draft_remove, name="draft_remove"),
    url(r"^post/(?P<pk>\d+)/tag/$", views.tag_post, name="tag_post"),
    url(
        r"^post/(?P<pk>\d+)/comment/$",
        views.add_comment_to_post,
        name="add_comment_to_post",
    ),
    url(
        r"^comment/(?P<pk>\d+)/approve/$", views.comment_approve, name="comment_approve"
    ),
    url(r"^comment/(?P<pk>\d+)/remove/$", views.comment_remove, name="comment_remove"),
    url(r"^test/$", views.post_test, name="post_test"),
]

dmlgeo/urls.py
from django.conf.urls import url
from . import views

app_name = "dmlgeo"

urlpatterns = [
    # url(r'^$', views.chat_main, name='chat'),
    # url(r'^test/$', views.chat_test, name='test'),
]

dmlmain/urls.py
from django.conf.urls import include
from django.urls import path, re_path
# from django.conf import settings
# from django.conf.urls.static import static
import django.contrib.auth.views

from .views import homepage, contact_admins, django_admin_page, register, contact_jinja, GenerateInvoice, GeneratePdf


urlpatterns = [
    path(r"", homepage, name="homepage"),
    re_path(r"^contact/$", contact_admins, name="contact_admins"),
    re_path(
        r"^admin/$", django_admin_page, name="django_admin_page"
    ),  # link to admin
    re_path(r"^accounts/", include("registration.backends.default.urls")),
    # names = 'auth_login' /login 'auth_logout' 'registration_register' 'auth_password_reset' 'registration_activate'
    re_path(r"accounts/register/$", register, name="register"),
    re_path(r"accounts/login/$", django.contrib.auth.views.LoginView, name="login"),
    re_path(
        r"accounts/logout/$",
        django.contrib.auth.views.LogoutView,
        name="logout",
        kwargs={"next_page": "/"},
    ),
    re_path(r"^test/$", GeneratePdf.as_view(), name="test"),
    re_path(r"^invoice/$", GenerateInvoice.as_view(), name="invoice"),
    re_path(r"^contactjn/$", contact_jinja, name="contact_jinja"),
]

dmlpolls/urls.py
from django.conf.urls import url
from . import views

app_name = 'dmlpolls'
urlpatterns = [
    # url(r'^index$', views.PollIndexView.as_view(), name='poll_index'),
    # url(r'^(?P<pk>[0-9]+)/$', views.PollDetailView.as_view(), name='poll_detail'),
    # url(r'^(?P<pk>[0-9]+)/results/$', views.PollResultsView.as_view(), name='poll_results'),


    url(r'^$', views.poll_list, name='poll_list'),
    url(r'^(?P<pk>[0-9]+)/$', views.poll_detail, name='poll_detail'),
    url(r'^question/add/$', views.addpoll, name='add_poll'),
    url(r'^(?P<question_id>[0-9]+)/add_choice/$', views.add_choice, name='add_choice'),
    url(r'^(?P<pk>[0-9]+)/vote/$', views.vote, name='poll_vote'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.results, name='poll_results'),

    # url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    # url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

dmlsite/urls.py
from django_jinja import views as dj_jn_views
from django.conf.urls import url, include
from django.urls import re_path, path
# import django.contrib.auth.views    # The login views redirect to admin here, or to previous page in dmlmain
from django.contrib import admin
# from django.contrib.staticfiles.storage import staticfiles_storage
# from django.views.generic.base import RedirectView
from controlcenter.views import controlcenter
from django.conf.urls.static import static
from django.conf import settings

from typing import cast

urlpatterns = [
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    path('admin/dashboard/', controlcenter.urls),
    # url(r'^accounts/login/$', django.contrib.auth.views.login, name='login'),
    # url(r'^accounts/logout/$', django.contrib.auth.views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('dmlmain.urls')),
    url(r'^blog/', include('dmlblog.urls', namespace='blog')),
    re_path(r'^polls/', include('dmlpolls.urls', namespace='polls')),
    url(r'^comments/', include('dmlcomments.urls', namespace='comments')),
    url(r'^research/', include('dmlresearch.urls', namespace='research')),
    url(r'^chat/', include('dmlchat.urls', namespace='chat')),
]


# handler400 = dj_jn_views.BadRequest.as_view()
# handler403 = dj_jn_views.PermissionDenied.as_view()
handler404 = dj_jn_views.PageNotFound.as_view()
# handler500 = dj_jn_views.ServerError.as_view()

if settings.DEBUG: 
    urlpatterns += static(cast(str, settings.STATIC_URL), document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dmlmain/models.py
from django.db import models


class SignUp(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=200, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self) -> str:
        # reveal_type(self.email)
        return str(self.email)

dmlmain/forms.py
from django import forms
from .models import SignUp


class SignUpForm(forms.ModelForm):
    class Meta:
        model = SignUp
        fields = ["name", "email"]

    def clean_email(self) -> str:
        email: str = self.cleaned_data.get("email")
        # domain, extension = provider.split('.')
        # if domain == "dmlsite":
        # 	raise forms.ValidationError("Already have email")
        # if extension != "ac.uk":
        # 	...
        return email

    def clean_name(self) -> str:
        name: str = self.cleaned_data.get("name")
        return name


class ContactForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=200)

dmlmain/views.py
# from django.template.loader import get_template
# import os
# from twilio.rest import Client

# from .tasks import create_html_report, email_report
# from django_q.tasks import async_task, result
from django.contrib.auth.decorators import login_required
from django.shortcuts import render  # , redirect, get_object_or_404

# from datetime import timezone
from django.core.mail import send_mail
from django.conf import settings
from .forms import SignUpForm, ContactForm
from .models import SignUp
from django.http import HttpResponse, HttpRequest
from django.core.handlers.wsgi import WSGIRequest
from django.views.generic import View
from dmlmain.utils import render_to_pdf
import datetime
from django_user_agents.utils import get_user_agent

from typing import Any


def homepage(request: WSGIRequest) -> HttpResponse:
    form = SignUpForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        # if not instance.name:
        # instance.name = "Visitor"
        # name = form.cleaned_data.get("name")
        instance.save()
        # 'text' is name of template tag, text is what is shown

    if request.user.is_authenticated and request.user.is_staff:
        text = f"Hello {request.user}, valued employee, printing signups "
        i = 1
        for instance in SignUp.objects.all():
            print(i)
            print(instance)
            i += 1
    elif request.user.is_authenticated:
        text = f"Hello {request.user}"
    else:
        text = "Welcome visitor"
    context = {"text": text, "form": form}
    user_agent = get_user_agent(request)
    if user_agent.is_mobile is False:
        return render(request, "dmlmain/homepage.html", context)
    else:
        # return render(request, 'dmlmain/homepage_mob.html', context)
        return HttpResponse("you are on a mobile")


def contact_admins(request: WSGIRequest) -> HttpResponse:
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form_name = form.cleaned_data.get("name")
        form_email = form.cleaned_data.get("email")
        form_message = form.cleaned_data.get("message")
        subject = "dmlsite contact"
        from_email = settings.EMAIL_HOST_USER
        to_email = [from_email, form_email]  # send copy to myself
        contact_message = "%s: %s via %s" % (form_name, form_message, from_email)
        send_mail(subject, contact_message, from_email, to_email, fail_silently=False)
        # async_task('dmlmain.tasks.create_html_report', , hook='dmlmain.tasks.test_hook')
    context = {"form": form}
    return render(request, "dmlmain/contact_admins.html", context)


def contact_jinja(request: HttpRequest) -> HttpResponse:
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form_name = form.cleaned_data.get("name")
        form_email = form.cleaned_data.get("email")
        form_message = form.cleaned_data.get("message")
        subject = "dmlsite contact"
        from_email = settings.EMAIL_HOST_USER
        to_email = [from_email, form_email]  # send copy to myself
        contact_message = "%s: %s via %s" % (form_name, form_message, from_email)
        send_mail(subject, contact_message, from_email, to_email, fail_silently=False)
        # async_task('dmlmain.tasks.create_html_report', , hook='dmlmain.tasks.test_hook')
    context = {"form": form}
    return render(request, "dmlmain/contact_jinja.jinja", context)


"""
def contact_SMS(request: HttpRequest) -> HttpResponse:
    form = SMSForm(request.POST or None)
    if form.is_valid():
        form_name = form.cleaned_data.get("name")
        form_email = form.cleaned_data.get("email")
        form_message = form.cleaned_data.get("message")
        PHONE_NUMBER = os.environ["PHONE_NUMBER"]
        TWILIO_NUMBER = os.environ["TWILIO_NUMBER"]
        TWILIO_ACC_SID = os.environ["TWILIO_ACC_SID"]
        TWILIO_AUTH_TOKEN = os.environ["TWILIO_AUTH_TOKEN"]
        client = Client(TWILIO_ACC_SID, TWILIO_AUTH_TOKEN)
        client.messages.create(
            to=PHONE_NUMBER,
            from_=TWILIO_NUMBER,
            body="%s: %s via %s" % (form_name, form_message, form_email),
        )
    context = {"form": form}
    return render(request, "dmlmain/contact_SMS.html", context)
"""


@login_required
def django_admin_page(request: HttpRequest) -> HttpResponse:
    return render(request, "dmlmain/admin")


def register(request: HttpRequest) -> HttpResponse:
    return render(request, "registration/registration_form.html")


class GenerateInvoice(View):
    def get(
        self, request: HttpRequest, name: str = "Default", *args: Any, **kwargs: Any
    ) -> HttpResponse:
        if "amount" in kwargs:
            amount = kwargs["amount"]
        else:
            amount = None
        invoice_id = 12345

        context = {
            "today": datetime.date.today(),
            "amount": amount,
            "customer_name": name,
            "invoice_id": invoice_id,
        }
        pdf = render_to_pdf("pdf/test.html", context)
        return HttpResponse(pdf, content_type="application/pdf")


class GeneratePdf(View):
    def get(
        self, request: HttpRequest, name: str = "Default", *args: Any, **kwargs: Any
    ) -> HttpResponse:
        # template = get_template("pdf/test.html")
        # = Invoice.amount etc from a model. Then can be added by form
        if "amount" in kwargs:
            amount = kwargs["amount"]
        else:
            amount = None
        invoice_id = 12345
        customer_name = name
        context = {
            "invoice_id": invoice_id,
            "customer_name": customer_name,
            "amount": amount,
            "today": datetime.date.today(),
        }
        # html = template.render(context)
        pdf = render_to_pdf("pdf/test.html", context)
        if pdf:
            response = HttpResponse(pdf, content_type="application/pdf")
            filename = "Invoice_%s.pdf" % ("company_name " + str(invoice_id))
            content = "inline; filename='%s'" % (filename)
            download = request.GET.get("download")
            if download:
                content = "attachment; filename='%s'" % (filename)
            response["Content-Disposition"] = content
            return response
        return HttpResponse("Not found")

        # response = HttpResponseRedirect("URL u want to redirect to"
        # response['Content-Disposition'] = "attachment; filename='%s'" % ("attachment; filename='yourpdffilename')
        # return response﻿


def handler404(request):
    return render(request, '404.html', status=404)
    

def handler500(request):
    return render(request, '500.html', status=500)

dmlmain/templates/dmlmain/base.html
<html>
<head>

<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>DMLsite</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">

{% load static %}
{% load sitetree %}
{% load cookielaw_tags %}
{% load compress %}
{% load socialaccount %}




{% compress css file base%}
<link rel="stylesheet" href="{% static 'dmlmain/css/vendor/bootstrap.min.css' %}"/>
<link rel="stylesheet" href="{% static 'dmlmain/css/vendor/font-awesome.min.css' %}"/>
<link rel="stylesheet" href="{% static 'dmlmain/css/dmlmain.scss' %}"/>
{% endcompress %}

{% compress js file base %}
<script src="{% static 'dmlmain/js/vendor/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'dmlmain/js/vendor/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'dmlmain/js/homepage.js' %}"></script>
{% endcompress %}

<link rel="icon"  type="image/x-icon" href="{% static 'dmlmain/icons/favicon.ico' %}"/>

{% block head_extra %} {% endblock head_extra %}
</head>

<body>

    <div class="header_footer .col-md-12">
    <div class="container page-header header_footer">
				<a href="{% url 'contact_admins' %}" class="top-menu" data-toggle="tooltip" title="Contact" data-placement="auto bottom"><span class="glyphicon glyphicon-phone-alt"></span></a>
        {% if user.is_authenticated %}
				<a id="logout" href="{% url 'logout' %}?next={{request.path}}" class="top-menu btn btn-success">Logout</a>

            	<a href="{% url 'blog:post_new' %}" class="top-menu" data-toggle="tooltip" title="Write post" data-placement="auto bottom"><span class="glyphicon glyphicon-pencil"></span></a>
				<a href="{% url 'polls:add_poll' %}" class="top-menu" data-toggle="tooltip" title="Create Poll" data-placement="auto bottom"><span class="glyphicon glyphicon-plus"></span></a>
				<a href="{% url 'blog:post_draft_list' %}" class="top-menu" data-toggle="tooltip" title="See draft posts" data-placement="auto bottom"><span class="glyphicon glyphicon-edit"></span></a>
				<a href="{% url 'django_admin_page' %}" class="top-menu" data-toggle="tooltip" title="Admin" data-placement="auto bottom"><span class="glyphicon glyphicon-cog"></span></a>
				<p class="top-menu2">Hello {{ user.username }}.<small>(<a href="{% url 'logout' %}?next={{request.path}}">Log out</a>)</small> {% now "SHORT_DATETIME_FORMAT" %}</p>
				<p><a href="{% provider_login_url "twitter" process="connect" %}">Connect a social account</a></p>
			{% else %}
			{% if not "/accounts/login" in request.get_full_path %}
				<form class='navbar-form' method='POST' action='{% url "auth_login" %}'> {% csrf_token %}
					<div class='form-group'>
						<input type='text' class='form-control' name='username' placeholder='Username' />
						<input type='text' class='form-control' name='password' placeholder='Password' />

					<button type='submit' class='btn btn-default'>Login</button>
				</form>
				    	<a id="twitter_login" href="/accounts/twitter/login" class="btn btn-success">Sign in with Twitter</a>
						<a id="github_login" href="/accounts/github/login" class="btn btn-success">Sign in with Github</a>

				    </div>

			{% endif %}
				<a href="{% url 'login' %}?next={{request.path}}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
				<a href="{% url 'register' %}" class="top-menu"><span class="glyphicon glyphicon-list-alt"></span></a>
		{% endif %}


<h1>
	<a href="/">DML</a>
	<a href="/blog">Blog</a> /
	<a href="/polls">Polls</a> /
	<a href="/chat">Chat</a>
</h1>
	</div>
	</div>

	<div class = "sidenav">
		<div class = "col-md-1">
		{% sitetree_menu from "main_tree" include "trunk" %}
		</div>
	</div>

	<br>

{% include "dmlmain/messages.html" %}
	<div class="container">
        <div class="row">
            <div class="contentcentre col-md-6">

				{% block content %}
				{% endblock %}
				{% block allauth %}
				{% endblock %}

            </div>
        </div>
	</div>


<br>
<br>
<br>

</body>


<div class="header_footer">
<footer>
{% cookielaw_banner %}
	<p class="bottom-menu2">Contact information: <a href="mailto:yobmod@gmail.com">yobmod@gmail.com</a>  <i class="fa fa-bolt fa-spin"></i></p>
</footer>
</div>


</html>

dmlmain/templates/dmlmain/base.jinja
<html>
<head>

<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>DMLsite</title>
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% block head_extra %} {% endblock head_extra %}

{% compress css %}
<link rel="stylesheet" href="{{ static('dmlmain/css/vendor/bootstrap.min.css') }}"/>
<link rel="stylesheet" href="{{ static('dmlmain/css/vendor/font-awesome.min.css') }}"/>
{% endcompress %}

{% compress js %}
<script src="{{ static('dmlmain/js/vendor/jquery-3.2.1.min.js') }}" type="text/javascript" ></script>
<script src="{{ static('dmlmain/js/vendor/bootstrap.min.js') }}" type="text/javascript" ></script>
<script src="{{ static('dmlmain/js/homepage.js') }}" type="text/javascript" defer></script>
{% endcompress %}

<link rel="icon" type="image/x-icon" href="{{ static('dmlmain/icons/favicon.ico') }}"/>

</head>


<body>

<h1>
	<a href="/">DML</a>
	<a href="/blog">Blog</a> /
	<a href="/polls">Polls</a> /
	<a href="/chat">Chatttt</a>
</h1>
{{ clb() }}
<br>

{% block content %} {% endblock content %}


</body>

</html>

dmlmain/templates/dmlmain/base_mob.html
<html>
<head>

<meta charset="utf-8">
<title>DMLsite</title>
<meta name="viewport" content="width=device-width, initial-scale=1">

{% load static %}
{% load sitetree %}
{% load cookielaw_tags %}
{% load compress %}


<!--<link rel="stylesheet" href="{% static 'dmlmain/css/vendor/normalize.css' %}"/>
<!--<link rel="stylesheet" href="{% static 'dmlmain/css/vendor/font-awesome.min.css' %}"/>
<link rel="stylesheet" href="{% static 'dmlmain/css/vendor/bootstrap.min.css' %}"/>-->
{% compress css %}
<link rel="stylesheet" href="{% static 'dmlmain/css/vendor/font-awesome.min.css' %}"/>
<link rel="stylesheet" href="{% static 'dmlmain/css/vendor/bootstrap.min.css' %}" />
<link rel="stylesheet" href="{% static 'dmlmain/css/dmlmain.scss' %}"/>
{% endcompress %}

<script src='dmlmain/js/vendor/jquery-3.1.1.min.js'></script>
<script>window.jQuery || document.write('<script src="{% static 'dmlmain/js/vendor/jquery-3.1.1.min.js' %}"><\/script>')</script>
<script src='dmlmain/js/vendor/bootstrap.min.js'></script>
<script>window.jQuery.fn.modal || document.write('<script src="{% static 'dmlmain/js/vendor/bootstrap.min.js' %}"><\/script>')</script>
<!--<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
<!--<script>try{Modernizr} catch(e) {document.write('<script src="./assets/js/vendor/modernizr-2.8.3.min.js"><\/script>')}</script>
-->
<link rel="icon" href="{% static 'dmlmain/icons/favicon.ico' type="image/x-icon" %}"/>

{% block head_extra %} {% endblock head_extra %}
</head>

<body>

    <div class="header_footer .col-md-12">
    <div class="page-header header_footer">
				<a href="{% url 'contact_admins' %}" class="top-menu" data-toggle="tooltip" title="Contact" data-placement="auto bottom"><span class="glyphicon glyphicon-phone-alt"></span></a>
        {% if user.is_authenticated %}
            	<a href="{% url 'blog:post_new' %}" class="top-menu" data-toggle="tooltip" title="Write post" data-placement="auto bottom"><span class="glyphicon glyphicon-pencil"></span></a>
				<a href="{% url 'polls:add_poll' %}" class="top-menu" data-toggle="tooltip" title="Create Poll" data-placement="auto bottom"><span class="glyphicon glyphicon-plus"></span></a>
				<a href="{% url 'blog:post_draft_list' %}" class="top-menu" data-toggle="tooltip" title="See draft posts" data-placement="auto bottom"><span class="glyphicon glyphicon-edit"></span></a>
				<a href="{% url 'django_admin_page' %}" class="top-menu" data-toggle="tooltip" title="Admin" data-placement="auto bottom"><span class="glyphicon glyphicon-cog"></span></a>
				<p class="top-menu2">Hello {{ user.username }}.<small>(<a href="{% url 'logout' %}?next={{request.path}}">Log out</a>)</small> {% now "SHORT_DATETIME_FORMAT" %}</p>
		{% else %}
			{% if not "/accounts/login" in request.get_full_path %}
				<form class='navbar-form' method='POST' action='{% url "auth_login" %}'> {% csrf_token %}
					<div class='form-group'>
						<input type='text' class='form-control' name='username' placeholder='Username' />
						<input type='text' class='form-control' name='password' placeholder='Password' />
					</div>
					<button type='submit' class='btn btn-default'>Login</button>
			{% endif %}
				<a href="{% url 'login' %}?next={{request.path}}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
				<a href="{% url 'register' %}" class="top-menu"><span class="glyphicon glyphicon-list-alt"></span></a>
		{% endif %}


				<h1><a href="/">DML</a>-mobile!-<a href="/blog">Blog</a> / <a href="/polls">Polls</a> </h1>
	</div>
	</div>

	<div class = "sidenav">
		<div class = "col-md-1">
		{% sitetree_menu from "main_tree" include "trunk" %}
		</div>
	</div>

	<br>

{% include "dmlmain/messages.html" %}
	<div class="content container">
        <div class="row">
            <div class="contentcentre col-md-6">

				{% block content %}
				{% endblock %}

            </div>
        </div>
	</div>


<br>
<br>
<br>

</body>


<div class="header_footer">
<footer>
{% cookielaw_banner %}
	<p class="bottom-menu2">Contact information: <a href="mailto:yobmod@gmail.com">yobmod@gmail.com</a>  <i class="fa fa-bolt fa-spin"></i></p>
</footer>
</div>

<script type="text/javascript" src="{% static 'dmlmain/js/homepage.js' %}" defer></script>
</html>

dmlmain/templates/dmlmain/contact_admins.html
{% extends 'dmlmain/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="contact">
        <p> If you have any comments or queries, please contact the webmaster using one of the following methods:</p>
		<br>
		<span class="glyphicon glyphicon-envelope"></span>
		<br>
		<br>
		<br>
		<span class="glyphicon glyphicon-phone"></span>

		<form method='POST' action=''>{%csrf_token %}
		{{form|crispy}}
		<input type='submit', value='Submit'/>

		<br>
		<br>
		<br>
		<div class ="contact">
		<a href="https://www.paypal.me/dmlsite"><img src= "{% static "dmlmain/images/donate-button.png" %}" alt="Paypal donate" style="width:210px;height:105px;border:0;"/></a>
		</div>

    </div>
{% endblock %}

dmlmain/templates/dmlmain/contact_jinja.jinja
{% extends 'base.jinja' %}


{% block content %}

    <div class="contact">
        <p> If you have any comments or queries, please contact the webmaster using one of the following methods:</p>
		<br>
		<span class="glyphicon glyphicon-envelope"></span>
		<br>
		<br>
		<br>
		<span class="glyphicon glyphicon-phone"></span>

		<form method='POST' action=''>{% csrf_token %}
		{{ form|crispy(template_pack=bootstrap4) }}
		<input type='submit', value='Submit'/>

		<br>
		<br>
		<br>
		<div class ="contact">
		<a href="https://www.paypal.me/dmlsite"><img src= "{{ static('dmlmain/images/donate-button.png') }}" alt="Paypal donate" style="width:210px;height:105px;border:0;"/></a>
		</div>

    </div>

{% endblock %}

dmlmain/templates/dmlmain/homepage.html
{% extends 'dmlmain/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load urlify %}

{% block content %}



	<div>
		<h1>{{text}}</h1>

		<h1>This is the homepage of my site.

		Click <a href="/blog">here</a> for posts

		Click <a href="/polls">here</a> for polls</h1>

		<img class="randomfade" style="opacity:0;" src="https://i.ytimg.com/vi/EmZ8Fq2zhZU/hqdefault.jpg"/>
	</div>

	{% if not user.is_authenticated %}
	<div>

		<form method='POST' action='' class="post-form">{%csrf_token %}
		{{form|crispy}}
		<input type='submit', value='Sign Up'/>

	</div>
	{% endif %}

	<div class="social_links">
	Share this site to: <span><a href = "https://facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">Facebook</a>
	<a href = "https://twitter.com/home?status={{ instance.content|urlify}}%20{{ request.build_absolute_uri }}">Twitter</a>
	</span>
	</div>

	<div class="fb-comments" data-href= "{{ request.build_absolute_uri }}"  data-numposts="5">
	</div>

	<div id="fb-root">
		<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.8";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	</div>




{% endblock %}

dmlmain/templates/dmlmain/messages.html
{% if messages %}<ul class="messages">
	{% for message in messages %}
				<li{% if message.tags %} class="{{ message.tags  }}"{% endif %}>	{{message}}</li>
	{% endfor %}	</ul>
{% endif %}

dmlmain/templates/dmlmain/my_widget.html
<html>

<textarea id="mywidget-{{ widget.name }}" name="{{ widget.name }}">
{% if widget.value %}{{ widget.value }}{% endif %}</textarea>

</html>